# Generated by Django 4.2.4 on 2023-08-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productheroimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productheroimages',
            options={'verbose_name_plural': 'Product Hero Images'},
        ),
    ]
